const icons={spark:'<path d="m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',desktop:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',data:'<path d="M4 6c0-4 16-4 16 0s-16 4-16 0v12c0 4 16 4 16 0V6M4 12c0 4 16 4 16 0"/>',link:'<path d="m10 13 4-4m-6 6-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 6a4 4 0 0 0 6 0l3-3a4 4 0 0 0-6-6l-1 1"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',back:'<path d="m14 6-6 6 6 6"/>',arrow:'<path d="m9 6 6 6-6 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>',cloud:'<path d="M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13 2 4 4 0 1 1 0 8Z"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',plus:'<path d="M12 5v14M5 12h14"/>',folder:'<path d="M3 7V5h7l2 3h9v12H3V7Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.spark}</svg>`;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={llm:'AI assistant',embedding:'Semantic search',voice:'Voice input'};
const hints={llm:'Discuss ideas, recall memories, and keep them up to date.',embedding:'Find related memories even with different wording.',voice:'Speak to capture an idea or ask a question.'};
let state,route='ai',draft=null,toastTimer,epoch=0,indexTimer;const timers=new Set();
function later(fn,ms){const e=epoch;const t=setTimeout(()=>{timers.delete(t);if(e===epoch)fn()},ms);timers.add(t);return t}
function reset(scenario='daily'){
 epoch++;for(const t of timers)clearTimeout(t);timers.clear();draft=null;
 state={services:scenario==='new'?[]:[{id:'silicon',name:'SiliconFlow',url:'https://api.siliconflow.cn/v1',preset:'silicon'}],llm:{enabled:scenario!=='new',source:'service',service:'silicon',model:'Qwen3.5-Plus'},embedding:{enabled:scenario!=='new',source:'local',service:'silicon',model:'Qwen3-Embedding · 0.6B',downloaded:scenario!=='new',progress:scenario==='new'?0:128,job:null},voice:{enabled:scenario!=='new',source:scenario==='error'?'service':'local',service:'silicon',model:scenario==='error'?'SenseVoiceSmall':'Qwen3-ASR · 0.6B',downloaded:scenario!=='new',error:scenario==='error',preload:false},organize:true,desktop:true,startup:false,mcp:false,shortcut:'⌃ ⌘ M',voiceShortcut:'⌃ ⇧ Space',record:null};
 route=scenario==='error'?'voice':'ai';$('settings-shade').hidden=false;if($('modal').open)$('modal').close();$('scenario').value=scenario;render();if(scenario==='error'){draftFor('voice');state.record='failed';render()}
}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function navigate(next){draft=null;route=next;if(names[next])draftFor(next);render();$('page').scrollTop=0}
function draftFor(key){draft={...state[key],tested:false,result:null,testing:false}}
function sw(key,label,value){return `<button class="switch" role="switch" aria-label="${label}" aria-checked="${!!value}" data-action="toggle" data-key="${key}"><span></span></button>`}
function btn(text,action,cls='',attrs=''){return `<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`}
function sourceBadge(source){return `<span class="badge ${source==='local'?'local':'remote'}">${source==='local'?'On this Mac':'API service'}</span>`}
function serviceName(id){return state.services.find(s=>s.id===id)?.name||'Not connected'}
function header(title,sub,back=false){$('page-header').innerHTML=`<div class="heading-content">${back?`<button class="icon-button back" data-action="back" aria-label="Back to AI & models">${icon('back')}</button>`:''}<div><h2>${title}</h2><p>${sub}</p></div></div><button class="icon-button" data-action="close-settings" aria-label="Close settings">${icon('close')}</button>`}
function footer(left,right=''){ $('page-footer').innerHTML=`<span>${left}</span>${right}` }
function render(){
 const active=['llm','embedding','voice'].includes(route)?'ai':route;
 $('nav').innerHTML=[['ai','spark','AI & models'],['desktop','desktop','Quick entry'],['data','data','Data & storage'],['mcp','link','External access']].map(([key,i,label])=>`<button class="nav-item ${active===key?'active':''}" data-action="navigate" data-page="${key}" ${active===key?'aria-current="page"':''}>${icon(i)}${label}</button>`).join('');
 if(route==='ai')renderOverview();else if(names[route])renderDetail();else if(route==='desktop')renderDesktop();else if(route==='data')renderData();else renderMcp();
}
function statusText(key){const s=state[key];if(!s.enabled)return 'Off';if(s.error)return 'Transcription incomplete';if(s.job)return s.job==='paused'?'Preparation paused':'Preparing';return key==='embedding'?`${s.progress} / 128 memories ready`:'Ready'}
function renderOverview(){header('AI & models','Choose the right model for each task.');$('page').innerHTML=Object.keys(names).map(key=>{const s=state[key];return `<section class="capability"><div class="cap-icon">${icon({llm:'spark',embedding:'search',voice:'mic'}[key])}</div><div class="cap-content"><div class="cap-title"><h3>${names[key]}</h3>${s.enabled?sourceBadge(s.source):''}</div><p>${hints[key]}</p><div class="model-line">${s.enabled?`${esc(s.source==='service'?(s.url||serviceName(s.service))+' · ':'')}${esc(s.model)}`:key==='llm'?'Connect a model with your API settings':key==='embedding'?'Recommended local model · Download about 640 MB':'Recommended local model · Download about 1.02 GB'}</div></div><div class="cap-side"><span class="${s.error?'error-text':s.enabled?'ready':'badge'}">${statusText(key)}</span><button class="text-button" data-action="navigate" data-page="${key}">${s.enabled?'Manage':'Set up'}${icon('arrow')}</button></div></section>`}).join('')+`<p class="subtle-note">${icon('lock')}Capture, edit, and use keyword search without a model.</p>`;footer('Model settings stay on this Mac')}
function renderDetail(){
 if(!draft)draftFor(route);const s=state[route],local=draft.source==='local',key=route;
 header(names[key],hints[key],true);
 let html=key==='llm'?`<div class="section-heading">Model service</div>`:`<div class="mode-picker">${[['local','desktop','On this Mac','Works offline after download'],['service','cloud','Use an API','Connect a provider or self-hosted service']].map(([mode,i,t,d])=>`<button class="mode-option ${draft.source===mode?'selected':''}" data-action="source" data-source="${mode}" aria-pressed="${draft.source===mode}">${icon(i)}<div><strong>${t}</strong><small>${d}</small></div><span class="radio"></span></button>`).join('')}</div>`;
 if(local){html+=`<div class="detail-card"><div class="detail-model"><div class="cap-icon">${icon(key==='voice'?'mic':'search')}</div><div><strong>${key==='voice'?'Qwen3-ASR':'Qwen3-Embedding'}</strong><p>0.6B · Q8 · ${key==='voice'?'Chinese, English, and other languages':'Multilingual semantic search'}</p></div><span class="badge local">Recommended</span></div><div class="row"><div><strong>${s.downloaded?'Downloaded':'Download required on first use'}</strong><p>${key==='voice'?'1.02 GB':'640 MB'} · ${s.downloaded?'Ready; loads when needed':'Works offline after download'}</p></div>${s.downloaded?`<span class="ready">${icon('check')}</span>`:btn(icon('download')+' Download model','download','','data-kind="'+key+'"')}</div><div id="download-status"></div></div>`;
 }else{
 html+=`<label class="form-field"><span>API address</span><input id="api-url" type="url" value="${esc(draft.url??state.services.find(s=>s.id===draft.service)?.url??'')}" placeholder="https://example.com/v1" autocomplete="off"></label><label class="form-field"><span>Model ID</span><input id="model-input" value="${esc(draft.model)}" placeholder="Enter a model ID" autocomplete="off"></label><label class="form-field"><span>API Key</span><input id="api-key" type="password" value="${esc(draft.apiKey??'')}" placeholder="Demo only. Do not enter a real key" autocomplete="off"></label><div class="button-row">${btn(draft.testing?'Testing…':'Test connection','test','',draft.testing?'disabled':'')}</div><div id="test-result">${draft.result?'<div class="test-result">Connection successful. This model is ready to use.</div>':''}</div>`;

 }
 html+=`<div class="privacy-note">${icon('lock')}<span>${local?'Content stays on this Mac and is not sent to a model service.':key==='llm'?'The selected service receives your messages and relevant memories to respond and update memories. Automatic note organization also sends new notes and relevant context.':key==='embedding'?'The selected service receives memory text and search queries, including updates and searches through MCP. Search data stays on this Mac.':'Audio is sent in segments to the selected service. Edit the transcript before submitting it as a memory.'}</span></div>`;
 if(key==='llm')html+=`<div class="toggle-block"><div class="row"><div><strong>Automatically organize saved notes</strong><p>Organize new notes after saving. Turning this off does not stop memory updates during chats. Notes saved while off will not be organized automatically when you turn it back on.</p></div>${sw('organize','Automatically organize saved notes',state.organize)}</div></div><details class="details"><summary>Advanced</summary><label class="form-field"><span>Output token limit</span><input type="number" min="1" placeholder="Use provider default" id="tokens" value="${esc(draft.tokens||'')}"></label><p>This Demo only previews parameters and does not call a real model.</p></details>`;
 if(key==='embedding')html+=`<div class="row"><div><strong>Search data</strong><p id="index-label">${s.enabled?statusText(key):'Prepare 128 memories for search when enabled.'}</p></div>${s.job?btn(s.job==='paused'?'Resume':'Pause','index-toggle'):s.enabled?`<button class="text-button" data-action="rebuild">Rebuild ${icon('arrow')}</button>`:''}</div><div id="index-progress">${s.job?progress(s.progress,128):''}</div><p class="subtle-note">Archives, history, trash, and unsaved drafts are excluded.</p>`;
 if(key==='voice')html+=`${s.enabled?`<div class="button-row">${btn(icon('mic')+' Try speaking','try-voice')}</div>`:''}<div id="recorder">${recordHTML()}</div>${local?`<details class="details"><summary>Local options</summary><div class="row"><div><strong>Prepare voice input at startup</strong><p>Prepare the model when Memivy starts to reduce the wait before recording.</p></div>${sw('preload','Prepare voice input at startup',state.voice.preload)}</div><button class="text-button" data-action="release">Unload voice model</button><p>Unloading frees RAM and keeps the downloaded files. The model loads again when you record.</p></details>`:''}<div class="row"><div><strong>Voice shortcut</strong><p>${state.voiceShortcut}</p></div><button class="text-button" data-action="navigate" data-page="desktop">Change shortcut ${icon('arrow')}</button></div>`;
 $('page').innerHTML=html;
 const changed=draft.source!==s.source||draft.model!==s.model||draft.service!==s.service||draft.url!==s.url;
 const canApply=local?s.downloaded:!!draft.model.trim()&&draft.tested;
 footer(s.enabled?`<button class="text-button" data-action="disable">Turn off ${names[key]}</button>`:'Turn this off anytime; saved content is unaffected',btn(key==='embedding'?(changed&&s.enabled?'Change and rebuild':s.enabled?'Apply settings':'Enable semantic search'):s.enabled?'Apply settings':'Enable '+names[key],'apply','primary',canApply?'':'disabled'));
}
function suggestions(key,id){if(key==='llm')return id==='ollama'?['qwen3.5:4b','gpt-oss:20b']:['Qwen3.5-Plus','My chat model'];if(key==='embedding')return id==='ollama'?['qwen3-embedding:0.6b','nomic-embed-text']:['Qwen/Qwen3-Embedding-0.6B','text-embedding-3-small'];return id==='qwen'?['qwen3-asr-flash']:['FunAudioLLM/SenseVoiceSmall','whisper-1']}
function progress(n,max){return `<div class="progress-track"><div class="progress-fill" style="width:${Math.round(n/max*100)}%"></div></div><div class="progress-label"><span>${n} / ${max}</span><span>${Math.round(n/max*100)}%</span></div>`}
function renderDesktop(){header('Quick entry','Capture ideas as they appear.');$('page').innerHTML=`<div class="section-heading">Open and type</div><div class="row"><div><strong>Open quick entry</strong><p>Press once to open, again to close.</p></div><button class="kbd" data-action="shortcut" data-kind="shortcut">${state.shortcut}</button></div><div class="row"><div><strong>Voice input</strong><p>Press once to record, again to stop.</p></div><button class="kbd" data-action="shortcut" data-kind="voiceShortcut">${state.voiceShortcut}</button></div><div class="row"><div><strong>Show floating button</strong><p>Keep the leaf on your desktop and drag it where it suits you.</p></div>${sw('desktop','Show floating button',state.desktop)}</div><div class="row"><div><strong>Start at login</strong><p>Start quietly with a menu bar entry.</p></div>${sw('startup','Start at login',state.startup)}</div><p class="subtle-note">${icon('info')}⌘ Enter submits; Enter inserts a new line. Closing the window keeps your draft.</p>`;footer('Shortcuts in this Demo are simulated')}
function renderData(){header('Data & storage','Memories stay local. You control your backups.');const size=(.036+(state.embedding.downloaded?.64:0)+(state.voice.downloaded?1.02:0)).toFixed(2);$('page').innerHTML=`<div class="detail-card"><div class="storage-total">${size} GB<small>Storage use</small></div><div class="storage-meter"><span></span><span style="${state.embedding.downloaded?'':'display:none'}"></span><span style="${state.voice.downloaded?'':'display:none'}"></span></div><div class="storage-key"><span>Memories and indexes 36 MB</span><span>Search model ${state.embedding.downloaded?'640 MB':'Not downloaded'}</span><span>Voice model ${state.voice.downloaded?'1.02 GB':'Not downloaded'}</span></div></div><div class="section-heading">Backup</div><div class="row"><div><strong>Back up library</strong><p>Includes memories, original notes, versions, conversations, and drafts. Keys are excluded.</p></div>${btn('Create backup','backup')}</div><div class="row"><div><strong>Restore backup</strong><p>A copy of the current library is created before restoring.</p></div>${btn('Choose backup','restore')}</div><details class="details"><summary>Manage local model files</summary><p>Delete downloaded models to free up space. Your memories are kept; you can download the models again when needed.</p>${['embedding','voice'].map(k=>`<div class="row"><div><strong>${k==='voice'?'Qwen3-ASR':'Qwen3-Embedding'}</strong><p>${state[k].downloaded?'Downloaded · Shared model files':'Not downloaded yet'}</p></div>${state[k].downloaded?btn('Delete files','clear-model','danger',`data-kind="${k}"`):''}</div>`).join('')}<div class="code">~/Library/Caches/com.memivy.app/models/</div></details><details class="details"><summary>Search maintenance</summary><div class="row"><div><strong>Repair search</strong><p>Try rebuilding search data if saved memories are missing from results.</p></div>${btn('Repair','repair')}</div><button class="text-button" data-action="navigate" data-page="embedding">Manage semantic search ${icon('arrow')}</button></details>`;footer('Storage values are simulated; no disk data is read')}
function renderMcp(){header('External access','Connect other AI apps to your saved memories.');$('page').innerHTML=`<div class="detail-card"><div class="detail-model"><div class="cap-icon">${icon('link')}</div><div><strong>Connect other AI apps</strong><p>Use MCP to save and search memories from other AI apps.</p></div>${sw('mcp','Allow other AI apps to save and search memories',state.mcp)}</div></div><div class="row"><div><strong>Save explicitly requested content</strong><p>Other AI apps can save text you explicitly ask them to remember.</p></div>${icon('check')}</div><div class="row"><div><strong>Search saved memories</strong><p>Returns a limited set of relevant excerpts and sources.</p></div>${icon('check')}</div><div class="privacy-note">${icon('info')}Other AI apps may send returned memories to their own model services. If semantic search uses an API, search queries are also sent to that service.</div><div class="button-row">${btn('View configuration','mcp-config','',state.mcp?'':'disabled')}${btn('Check local connection','mcp-test','',state.mcp?'':'disabled')}</div>`;footer('Turning this off stops new MCP calls and keeps existing memories')}
function openModal(title,body,actions=''){ $('modal').innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}`;$('modal').showModal()}
function closeModal(){if($('modal').open)$('modal').close()}
function apply(){const key=route,s=state[key];if(!draft)return;if(key==='embedding'&&(!s.enabled||draft.model!==s.model||draft.source!==s.source||draft.service!==s.service||draft.url!==s.url)){openModal(s.enabled?'Change semantic search model?':'Enable semantic search?',`<p class="modal-copy">${s.enabled?'Changing the model requires rebuilding the semantic index.':'An index will be built for your current memories.'} Capture, reading, and keyword search remain available.</p><div class="impact"><strong>128 current memories · About 64,000 characters</strong>${draft.source==='service'?`These content excerpts will be sent to: ${esc(draft.url??state.services.find(s=>s.id===draft.service)?.url??'the selected service')}. New and edited content is processed incrementally. Provider charges apply.`:'Processed on this Mac without uploading memory content.'}<br>Archives, history, trash, and drafts are excluded.</div>`,btn('Cancel','close-modal')+btn(s.enabled?'Change and rebuild':'Enable and index','confirm-index','primary'));return}state[key]={...s,...draft,enabled:true,error:false};toast(names[key]+' settings applied');navigate('ai')}
function beginIndex(){const s=state.embedding;s.job='indexing';s.progress=0;tickIndex();}
function tickIndex(){clearTimeout(indexTimer);indexTimer=later(()=>{const s=state.embedding;if(s.job!=='indexing')return;s.progress=Math.min(128,s.progress+16);if(s.progress===128){s.job=null;toast('Search is ready. You can search 128 memories by meaning.');render();return}if(route==='embedding'){$('index-label').textContent=`Indexing · ${s.progress} / 128 items`;$('index-progress').innerHTML=progress(s.progress,128)}else if(route==='ai')renderOverview();tickIndex()},550)}
function recordHTML(){if(!state.record)return '';const fail=state.record==='failed',recording=state.record==='recording',finishing=state.record==='finishing';return `<div class="record-card"><div class="record-head"><strong>${recording?'Recording':finishing?'Finishing transcription…':fail?'A segment is incomplete':'Transcription complete'}</strong><span class="badge ${state.voice.source==='local'?'local':'remote'}">${state.voice.source==='local'?'Local transcription':esc(serviceName(state.voice.service))+' transcription'}</span></div>${recording?`<div class="wave">${'<i></i>'.repeat(32)}</div><p class="modal-copy">This Demo does not use your microphone; it uses sample audio.</p>`:`<textarea id="voice-text" aria-label="Transcript">${esc(state.recordText??'I want to save ideas as they appear each day and organize them over the weekend.')}</textarea>`}${fail?'<p class="error-text">Connection interrupted. Recognized text and remaining audio are preserved.</p>':''}<div class="button-row">${recording?btn('Stop recording','stop-record','primary'):fail?btn('Retry remaining segments','retry-record','primary'):btn(finishing?'Please wait…':'Save this text','save-record','primary',finishing?'disabled':'')}${!recording&&!finishing?btn('Remove demo recording','clear-record'):''}</div></div>`}
function finishRecord(fail=false){state.record='finishing';$('recorder').innerHTML=recordHTML();later(()=>{state.record=fail?'failed':'done';state.voice.error=fail;$('recorder')&&($('recorder').innerHTML=recordHTML())},900)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,k=b.dataset.kind;
 if(a==='navigate')navigate(b.dataset.page);else if(a==='back')navigate('ai');else if(a==='close-settings')$('settings-shade').hidden=true;else if(a==='close-modal')closeModal();else if(a==='source'){if(draft.source===b.dataset.source)return;const remoteModel=draft.source==='service'?draft.model:draft.remoteModel;draft={...draft,remoteModel,testing:false,source:b.dataset.source,tested:false,result:null};draft.model=draft.source==='local'?(route==='voice'?'Qwen3-ASR · 0.6B':'Qwen3-Embedding · 0.6B'):(remoteModel??suggestions(route,draft.service)[0]);renderDetail()}
 else if(a==='toggle'){const key=b.dataset.key;if(key==='preload')state.voice.preload=!state.voice.preload;else state[key]=!state[key];b.setAttribute('aria-checked',key==='preload'?state.voice.preload:state[key]);if(key==='mcp')renderMcp();toast('Demo settings updated')}
 else if(a==='test'){if(!draft.model.trim()){toast('Enter a model ID first');return}const urlInput=$('api-url');if(!urlInput.value.trim()||!urlInput.checkValidity()){toast('Enter a valid API address');urlInput.focus();return}draft.testing=true;draft.result=null;const current=draft,model=draft.model,service=draft.service,url=draft.url,apiKey=draft.apiKey;renderDetail();later(()=>{if(draft!==current||draft.model!==model||draft.service!==service||draft.url!==url||draft.apiKey!==apiKey)return;draft.testing=false;draft.tested=true;draft.result='ok';renderDetail()},900)}
 else if(a==='apply')apply();else if(a==='confirm-index'){closeModal();state.embedding={...state.embedding,...draft,enabled:true};beginIndex();draftFor('embedding');renderDetail();toast('Building the semantic index. Keyword search remains available.')}
 else if(a==='index-toggle'){clearTimeout(indexTimer);state.embedding.job=state.embedding.job==='paused'?'indexing':'paused';if(state.embedding.job==='indexing')tickIndex();renderDetail()}
 else if(a==='rebuild'){draft.tested=true;draft.model=state.embedding.model;openModal('Rebuild semantic index?','<p class="modal-copy">This will process 128 current memories again. Content stays unchanged and keyword search remains available.</p>',btn('Cancel','close-modal')+btn('Start rebuild','confirm-index','primary'))}
 else if(a==='disable'){state[route].enabled=false;if(route==='embedding')state.embedding.job=null;toast(names[route]+' is off. Model files and memories are preserved.');navigate('ai')}
 else if(a==='download'){b.disabled=true;b.textContent='Downloading…';let n=0;const draw=()=>{n+=20;if(route===k&&$('download-status'))$('download-status').innerHTML=progress(n,100);if(n<100)later(draw,380);else{state[k].downloaded=true;toast('Model downloaded and ready to enable.');if(route===k)renderDetail()}};later(draw,300)}
 else if(a==='try-voice'){state.record='recording';state.recordText=undefined;$('recorder').innerHTML=recordHTML();$('recorder').scrollIntoView({block:'nearest',behavior:'smooth'})}
 else if(a==='stop-record')finishRecord($('scenario').value==='error');else if(a==='retry-record'){if($('voice-text'))state.recordText=$('voice-text').value;finishRecord(false)}else if(a==='save-record'){toast('Sample text saved to the demo. The real library is unchanged.');state.record=null;state.voice.error=false;$('recorder').innerHTML=''}else if(a==='clear-record'){state.record=null;state.voice.error=false;$('recorder').innerHTML=''}
 else if(a==='release')toast('Voice model unloaded in this demo. Downloaded files are kept; the model loads again when you record.');else if(a==='shortcut'){openModal('Set '+(k==='shortcut'?'quick-entry':'voice')+' shortcut','<p class="modal-copy">Click the box and press a key combination. This preview does not register a system shortcut.</p><button class="kbd" id="shortcut-input" style="width:100%">Click, then press a shortcut</button>');$('shortcut-input').onclick=()=>{$('shortcut-input').textContent='Press a shortcut…';$('shortcut-input').focus()};$('shortcut-input').onkeydown=e=>{if(['Control','Shift','Alt','Meta','Tab','Escape'].includes(e.key))return;e.preventDefault();state[k]=[e.ctrlKey?'⌃':'',e.altKey?'⌥':'',e.shiftKey?'⇧':'',e.metaKey?'⌘':'',e.code==='Space'?'Space':e.key.toUpperCase()].filter(Boolean).join(' ');closeModal();renderDesktop();toast('Shortcut updated in the demo')}}
 else if(a==='backup'){toast('Simulating backup…');later(()=>toast('Backup preview complete. No real data was read or exported.'),800)}else if(a==='restore')openModal('Restore from backup?','<p class="modal-copy">Sample backup: Memivy-2026-09-10.zip</p><div class="impact"><strong>Includes 124 memories and 18 conversations</strong>A copy of the current library is created before restoring. Model connections and keys stay unchanged.</div>',btn('Cancel','close-modal')+btn('Simulate restore','confirm-restore','primary'));
 else if(a==='confirm-restore'){closeModal();toast('Restore preview complete. The real library is unchanged.')}
 else if(a==='clear-model')openModal('Delete downloaded model?',`<p class="modal-copy">This frees ${k==='voice'?'1.02 GB':'640 MB'} of disk space. All Memivy libraries share this file; using the model again requires another download.</p><div class="impact">Current ${names[k]} will be disabled if it uses a local model. Memory content is preserved.</div>`,btn('Cancel','close-modal')+btn('Delete model files','confirm-clear','danger',`data-kind="${k}"`));
 else if(a==='confirm-clear'){state[k].downloaded=false;if(state[k].source==='local')state[k].enabled=false;if(k==='embedding')state.embedding.job=null;closeModal();renderData();toast('Simulated model cleanup. Memories preserved.')}
 else if(a==='repair'){toast('Simulating keyword index repair…');later(()=>toast('Keyword index repaired. Memory content is unchanged.'),800)}
 else if(a==='mcp-test'){b.disabled=true;b.textContent='Checking…';later(()=>{toast('Simulated check passed: capture and search work.');renderMcp()},700)}else if(a==='mcp-config')openModal('Local MCP configuration','<p class="modal-copy">Sample configuration below. The installed app generates its actual path.</p><div class="code">{\n  "mcpServers": {\n    "memivy": {\n      "command": "/Applications/Memivy.app/Contents/MacOS/memivy-mcp"\n    }\n  }\n}</div>',btn('Done','close-modal','primary'));
});
document.addEventListener('input',e=>{if(e.target.id==='model-input'&&draft){draft.model=e.target.value;draft.testing=false;const testButton=$('page').querySelector('[data-action=test]');if(testButton){testButton.disabled=false;testButton.textContent='Test connection'}draft.tested=false;draft.result=null;const applyButton=$('page-footer').querySelector('[data-action=apply]');if(applyButton)applyButton.disabled=true;$('test-result').innerHTML=''}if(e.target.id==='tokens'&&draft)draft.tokens=e.target.value;if(e.target.id==='voice-text')state.recordText=e.target.value});
$('scenario').onchange=e=>reset(e.target.value);$('reset').onclick=()=>{reset($('scenario').value);toast('Demo reset')};$('open-settings').onclick=()=>{$('settings-shade').hidden=false;navigate('ai')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').open&&!$('settings-shade').hidden){$('settings-shade').hidden=true;$('open-settings').focus()}});
reset();

document.addEventListener('input',e=>{if(draft&&['api-url','api-key'].includes(e.target.id)){draft[e.target.id==='api-url'?'url':'apiKey']=e.target.value;draft.testing=false;const testButton=$('page').querySelector('[data-action=test]');if(testButton){testButton.disabled=false;testButton.textContent='Test connection'}draft.tested=false;draft.result=null;const b=document.querySelector('[data-action="apply"]');if(b)b.disabled=true;$('test-result').innerHTML=''}});
