const icons={spark:'<path d="m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',desktop:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',data:'<path d="M4 6c0-4 16-4 16 0s-16 4-16 0v12c0 4 16 4 16 0V6M4 12c0 4 16 4 16 0"/>',link:'<path d="m10 13 4-4m-6 6-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 6a4 4 0 0 0 6 0l3-3a4 4 0 0 0-6-6l-1 1"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',back:'<path d="m14 6-6 6 6 6"/>',arrow:'<path d="m9 6 6 6-6 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>',cloud:'<path d="M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13 2 4 4 0 1 1 0 8Z"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',plus:'<path d="M12 5v14M5 12h14"/>',folder:'<path d="M3 7V5h7l2 3h9v12H3V7Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.spark}</svg>`;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={llm:'问答与整理',embedding:'语义检索',voice:'语音输入'};
const hints={llm:'回答问题，接着讨论，整理留下的想法。',embedding:'换一种说法，也能找回相关记忆。',voice:'开口记下想法，也可以直接提问。'};
let state,route='ai',draft=null,toastTimer,epoch=0,indexTimer;const timers=new Set();
function later(fn,ms){const e=epoch;const t=setTimeout(()=>{timers.delete(t);if(e===epoch)fn()},ms);timers.add(t);return t}
function reset(scenario='daily'){
 epoch++;for(const t of timers)clearTimeout(t);timers.clear();draft=null;
 state={services:scenario==='new'?[]:[{id:'silicon',name:'硅基流动',url:'https://api.siliconflow.cn/v1',preset:'silicon'}],llm:{enabled:scenario!=='new',source:'service',service:'silicon',model:'Qwen3.5-Plus'},embedding:{enabled:scenario!=='new',source:'local',service:'silicon',model:'Qwen3-Embedding · 0.6B',downloaded:scenario!=='new',progress:scenario==='new'?0:128,job:null},voice:{enabled:scenario!=='new',source:scenario==='error'?'service':'local',service:'silicon',model:scenario==='error'?'SenseVoiceSmall':'Qwen3-ASR · 0.6B',downloaded:scenario!=='new',error:scenario==='error',preload:false},organize:true,desktop:true,startup:false,mcp:false,shortcut:'⌃ ⌘ M',voiceShortcut:'⌃ ⇧ Space',record:null};
 route=scenario==='error'?'voice':'ai';$('settings-shade').hidden=false;if($('modal').open)$('modal').close();$('scenario').value=scenario;render();if(scenario==='error'){draftFor('voice');state.record='failed';render()}
}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function navigate(next){draft=null;route=next;if(names[next])draftFor(next);render();$('page').scrollTop=0}
function draftFor(key){draft={...state[key],tested:false,result:null,testing:false}}
function sw(key,label,value){return `<button class="switch" role="switch" aria-label="${label}" aria-checked="${!!value}" data-action="toggle" data-key="${key}"><span></span></button>`}
function btn(text,action,cls='',attrs=''){return `<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`}
function sourceBadge(source){return `<span class="badge ${source==='local'?'local':'remote'}">${source==='local'?'本机运行':'模型服务'}</span>`}
function serviceName(id){return state.services.find(s=>s.id===id)?.name||'未连接'}
function header(title,sub,back=false){$('page-header').innerHTML=`<div class="heading-content">${back?`<button class="icon-button back" data-action="back" aria-label="返回 AI 与模型">${icon('back')}</button>`:''}<div><h2>${title}</h2><p>${sub}</p></div></div><button class="icon-button" data-action="close-settings" aria-label="关闭设置">${icon('close')}</button>`}
function footer(left,right=''){ $('page-footer').innerHTML=`<span>${left}</span>${right}` }
function render(){
 const active=['llm','embedding','voice'].includes(route)?'ai':route;
 $('nav').innerHTML=[['ai','spark','AI 与模型'],['desktop','desktop','快捷入口'],['data','data','数据与存储'],['mcp','link','外部连接']].map(([key,i,label])=>`<button class="nav-item ${active===key?'active':''}" data-action="navigate" data-page="${key}" ${active===key?'aria-current="page"':''}>${icon(i)}${label}</button>`).join('');
 if(route==='ai')renderOverview();else if(names[route])renderDetail();else if(route==='desktop')renderDesktop();else if(route==='data')renderData();else renderMcp();
}
function statusText(key){const s=state[key];if(!s.enabled)return '未开启';if(s.error)return '转写未完成';if(s.job)return s.job==='paused'?'准备已暂停':'正在准备';return key==='embedding'?`已索引 ${s.progress} / 128 条`:'可用'}
function renderOverview(){header('AI 与模型','为不同的事，选择合适的模型。');$('page').innerHTML=Object.keys(names).map(key=>{const s=state[key];return `<section class="capability"><div class="cap-icon">${icon({llm:'spark',embedding:'search',voice:'mic'}[key])}</div><div class="cap-content"><div class="cap-title"><h3>${names[key]}</h3>${s.enabled?sourceBadge(s.source):''}</div><p>${hints[key]}</p><div class="model-line">${s.enabled?`${esc(s.source==='service'?(s.url||serviceName(s.service))+' · ':'')}${esc(s.model)}`:key==='llm'?'连接你自己的模型服务':key==='embedding'?'推荐本地模型 · 下载约 640 MB':'推荐本地模型 · 下载约 1.02 GB'}</div></div><div class="cap-side"><span class="${s.error?'error-text':s.enabled?'ready':'badge'}">${statusText(key)}</span><button class="text-button" data-action="navigate" data-page="${key}">${s.enabled?'管理':'设置'}${icon('arrow')}</button></div></section>`}).join('')+`<p class="subtle-note">${icon('lock')}不连接模型，也可以记录、编辑和使用基础搜索。</p>`;footer('模型配置只保存在这台 Mac')}
function renderDetail(){
 if(!draft)draftFor(route);const s=state[route],local=draft.source==='local',key=route;
 header(names[key],hints[key],true);
 let html=key==='llm'?`<div class="section-heading">使用的模型服务</div>`:`<div class="mode-picker">${[['local','desktop','内置本地模型','在这台 Mac 上运行'],['service','cloud','连接模型服务','自带 API 或自建服务']].map(([mode,i,t,d])=>`<button class="mode-option ${draft.source===mode?'selected':''}" data-action="source" data-source="${mode}" aria-pressed="${draft.source===mode}">${icon(i)}<div><strong>${t}</strong><small>${d}</small></div><span class="radio"></span></button>`).join('')}</div>`;
 if(local){html+=`<div class="detail-card"><div class="detail-model"><div class="cap-icon">${icon(key==='voice'?'mic':'search')}</div><div><strong>${key==='voice'?'Qwen3-ASR':'Qwen3-Embedding'}</strong><p>0.6B · Q8 · ${key==='voice'?'中文、英文及多语言':'多语言语义检索'}</p></div><span class="badge local">内置推荐</span></div><div class="row"><div><strong>${s.downloaded?'已下载':'首次使用需要下载'}</strong><p>${key==='voice'?'1.02 GB':'640 MB'} · ${s.downloaded?'准备就绪，使用时自动加载':'下载后可离线使用'}</p></div>${s.downloaded?`<span class="ready">${icon('check')}</span>`:btn(icon('download')+' 下载模型','download','','data-kind="'+key+'"')}</div><div id="download-status"></div></div>`;
 }else{
 html+=`<label class="form-field"><span>API 地址</span><input id="api-url" type="url" value="${esc(draft.url??state.services.find(s=>s.id===draft.service)?.url??'')}" placeholder="https://example.com/v1" autocomplete="off"></label><label class="form-field"><span>模型名称</span><input id="model-input" value="${esc(draft.model)}" placeholder="填写模型 ID" autocomplete="off"></label><label class="form-field"><span>API Key</span><input id="api-key" type="password" value="${esc(draft.apiKey??'')}" placeholder="演示用，请勿填写真实密钥" autocomplete="off"></label><div class="button-row">${btn(draft.testing?'正在测试…':'测试连接','test','',draft.testing?'disabled':'')}</div><div id="test-result">${draft.result?'<div class="test-result">连接通过，可以保存。</div>':''}</div>`;

 }
 html+=`<div class="privacy-note">${icon('lock')}<span>${local?'内容在这台 Mac 上处理，不发送到模型服务。':key==='llm'?'使用时发送问题、必要对话和相关记忆；开启自动整理后，也会发送新记录及相关背景。':key==='embedding'?'建立索引时发送当前记忆正文；之后发送新增或修改的内容和搜索问题。向量索引保存在本机。':'录音期间会分段发送音频到所选服务。转写文字可以修改，只有你提交后才保存为记忆。'}</span></div>`;
 if(key==='llm')html+=`<div class="toggle-block"><div class="row"><div><strong>保存后自动整理</strong><p>先保留原话，再整理到当前记忆；可以撤销。</p></div>${sw('organize','保存后自动整理',state.organize)}</div></div><details class="details"><summary>高级设置</summary><label class="form-field"><span>输出 token 上限</span><input type="number" min="1" placeholder="使用服务商默认值" id="tokens" value="${esc(draft.tokens||'')}"></label><p>本 Demo 仅预览参数设置，不调用真实模型。</p></details>`;
 if(key==='embedding')html+=`<div class="row"><div><strong>语义索引</strong><p id="index-label">${s.enabled?statusText(key):'开启后，从 128 条当前记忆建立索引。'}</p></div>${s.job?btn(s.job==='paused'?'继续':'暂停','index-toggle'):s.enabled?`<button class="text-button" data-action="rebuild">重新建立 ${icon('arrow')}</button>`:''}</div><div id="index-progress">${s.job?progress(s.progress,128):''}</div><p class="subtle-note">归档、历史、回收站和未保存草稿不参与索引。</p>`;
 if(key==='voice')html+=`${s.enabled?`<div class="button-row">${btn(icon('mic')+' 试说一句','try-voice')}</div>`:''}<div id="recorder">${recordHTML()}</div>${local?`<details class="details"><summary>本地运行选项</summary><div class="row"><div><strong>启动时预加载</strong><p>第一次开口少等一会。</p></div>${sw('preload','启动时预加载',state.voice.preload)}</div><button class="text-button" data-action="release">释放运行内存</button></details>`:''}<div class="row"><div><strong>语音快捷键</strong><p>${state.voiceShortcut}</p></div><button class="text-button" data-action="navigate" data-page="desktop">修改 ${icon('arrow')}</button></div>`;
 $('page').innerHTML=html;
 const changed=draft.source!==s.source||draft.model!==s.model||draft.service!==s.service||draft.url!==s.url;
 const canApply=local?s.downloaded:!!draft.model.trim()&&draft.tested;
 footer(s.enabled?`<button class="text-button" data-action="disable">关闭${names[key]}</button>`:'随时可以关闭，已保存的内容不受影响',btn(key==='embedding'?(changed&&s.enabled?'更换并重建':s.enabled?'应用设置':'启用语义检索'):s.enabled?'应用设置':'启用'+names[key],'apply','primary',canApply?'':'disabled'));
}
function suggestions(key,id){if(key==='llm')return id==='ollama'?['qwen3.5:4b','gpt-oss:20b']:['Qwen3.5-Plus','我的对话模型'];if(key==='embedding')return id==='ollama'?['qwen3-embedding:0.6b','nomic-embed-text']:['Qwen/Qwen3-Embedding-0.6B','text-embedding-3-small'];return id==='qwen'?['qwen3-asr-flash']:['FunAudioLLM/SenseVoiceSmall','whisper-1']}
function progress(n,max){return `<div class="progress-track"><div class="progress-fill" style="width:${Math.round(n/max*100)}%"></div></div><div class="progress-label"><span>${n} / ${max}</span><span>${Math.round(n/max*100)}%</span></div>`}
function renderDesktop(){header('快捷入口','在想法出现的时候，随手记下来。');$('page').innerHTML=`<div class="section-heading">唤起与输入</div><div class="row"><div><strong>打开快捷入口</strong><p>按一下打开，再按一下收起。</p></div><button class="kbd" data-action="shortcut" data-kind="shortcut">${state.shortcut}</button></div><div class="row"><div><strong>语音输入</strong><p>按一下开始录音，再按一下结束。</p></div><button class="kbd" data-action="shortcut" data-kind="voiceShortcut">${state.voiceShortcut}</button></div><div class="row"><div><strong>显示桌面助手</strong><p>让小叶子留在桌面，拖到顺手的位置。</p></div>${sw('desktop','显示桌面助手',state.desktop)}</div><div class="row"><div><strong>登录时启动</strong><p>安静启动，保留菜单栏入口。</p></div>${sw('startup','登录时启动',state.startup)}</div><p class="subtle-note">${icon('info')}⌘ Enter 提交，Enter 换行。关闭窗口会保留草稿。</p>`;footer('快捷键在此 Demo 中仅模拟设置')}
function renderData(){header('数据与存储','记忆留在本机，备份由你保管。');const size=(.036+(state.embedding.downloaded?.64:0)+(state.voice.downloaded?1.02:0)).toFixed(2);$('page').innerHTML=`<div class="detail-card"><div class="storage-total">${size} GB<small>本地占用</small></div><div class="storage-meter"><span></span><span style="${state.embedding.downloaded?'':'display:none'}"></span><span style="${state.voice.downloaded?'':'display:none'}"></span></div><div class="storage-key"><span>记忆与索引 36 MB</span><span>检索模型 ${state.embedding.downloaded?'640 MB':'未下载'}</span><span>语音模型 ${state.voice.downloaded?'1.02 GB':'未下载'}</span></div></div><div class="section-heading">备份</div><div class="row"><div><strong>备份记忆库</strong><p>包含记忆、原话、版本、讨论和草稿，不含密钥。</p></div>${btn('创建备份','backup')}</div><div class="row"><div><strong>从备份恢复</strong><p>恢复前会自动保留当前记忆库的副本。</p></div>${btn('选择备份','restore')}</div><details class="details"><summary>管理本地模型文件</summary><p>开发版、安装版与资料库共用这些文件。删除模型不会删除记忆，其他资料库使用时需要重新下载。</p>${['embedding','voice'].map(k=>`<div class="row"><div><strong>${k==='voice'?'Qwen3-ASR':'Qwen3-Embedding'}</strong><p>${state[k].downloaded?'已下载 · 共用模型文件':'尚未下载'}</p></div>${state[k].downloaded?btn('删除文件','clear-model','danger',`data-kind="${k}"`):''}</div>`).join('')}<div class="code">~/Library/Caches/com.memivy.app/models/</div></details><details class="details"><summary>搜索维护</summary><div class="row"><div><strong>修复基础搜索索引</strong><p>从当前记忆重新生成，不修改正文。</p></div>${btn('修复','repair')}</div><button class="text-button" data-action="navigate" data-page="embedding">管理语义索引 ${icon('arrow')}</button></details>`;footer('此处展示的是模拟占用，不读取真实磁盘')}
function renderMcp(){header('外部连接','让其他 AI 使用你在 Memivy 留下的记忆。');$('page').innerHTML=`<div class="detail-card"><div class="detail-model"><div class="cap-icon">${icon('link')}</div><div><strong>通过 MCP 连接</strong><p>标准本地连接，适用于支持 MCP 的应用。</p></div>${sw('mcp','允许 MCP 访问记忆',state.mcp)}</div></div><div class="row"><div><strong>保存明确要求记住的内容</strong><p>外部 AI 可以帮你把确认过的内容存进 Memivy。</p></div>${icon('check')}</div><div class="row"><div><strong>搜索已保存的记忆</strong><p>返回有限的相关片段及来源。</p></div>${icon('check')}</div><div class="privacy-note">${icon('info')}外部 AI 可能将返回的记忆发送给它使用的模型。Memivy 内的模型选择不会改变外部 AI 的配置。</div><div class="button-row">${btn('查看连接配置','mcp-config','',state.mcp?'':'disabled')}${btn('检查本地连接','mcp-test','',state.mcp?'':'disabled')}</div>`;footer('关闭后停止新的 MCP 调用，已有记忆保留')}
function openModal(title,body,actions=''){ $('modal').innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close-modal" aria-label="关闭弹窗">${icon('close')}</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}`;$('modal').showModal()}
function closeModal(){if($('modal').open)$('modal').close()}
function apply(){const key=route,s=state[key];if(!draft)return;if(key==='embedding'&&(!s.enabled||draft.model!==s.model||draft.source!==s.source||draft.service!==s.service||draft.url!==s.url)){openModal(s.enabled?'更换语义检索模型？':'开启语义检索？',`<p class="modal-copy">${s.enabled?'新的模型需要重新建立语义索引。':'将为你的当前记忆建立语义索引。'}过程中仍可记录、阅读和使用基础搜索。</p><div class="impact"><strong>128 条当前记忆 · 约 6.4 万字</strong>${draft.source==='service'?`这些正文片段将发送给「${esc(draft.url??state.services.find(s=>s.id===draft.service)?.url??'所填服务')}」。后续新增和修改也会增量处理，费用由服务商结算。`:'全部在这台 Mac 上处理，不上传记忆正文。'}<br>归档、历史、回收站与草稿不参与。</div>`,btn('取消','close-modal')+btn(s.enabled?'更换并重建':'启用并建立索引','confirm-index','primary'));return}state[key]={...s,...draft,enabled:true,error:false};toast(names[key]+'设置已应用');navigate('ai')}
function beginIndex(){const s=state.embedding;s.job='indexing';s.progress=0;tickIndex();}
function tickIndex(){clearTimeout(indexTimer);indexTimer=later(()=>{const s=state.embedding;if(s.job!=='indexing')return;s.progress=Math.min(128,s.progress+16);if(s.progress===128){s.job=null;toast('语义索引已就绪，128 条记忆可按含义检索。');render();return}if(route==='embedding'){$('index-label').textContent=`正在建立索引 · ${s.progress} / 128 条`;$('index-progress').innerHTML=progress(s.progress,128)}else if(route==='ai')renderOverview();tickIndex()},550)}
function recordHTML(){if(!state.record)return '';const fail=state.record==='failed',recording=state.record==='recording',finishing=state.record==='finishing';return `<div class="record-card"><div class="record-head"><strong>${recording?'正在录音':finishing?'正在完成转写…':fail?'有一段转写未完成':'转写完成'}</strong><span class="badge ${state.voice.source==='local'?'local':'remote'}">${state.voice.source==='local'?'本机识别':esc(serviceName(state.voice.service))+'识别'}</span></div>${recording?`<div class="wave">${'<i></i>'.repeat(32)}</div><p class="modal-copy">此 Demo 不开启麦克风，将使用示例语音。</p>`:`<textarea id="voice-text" aria-label="转写文字">${esc(state.recordText??'我想把每天冒出来的想法先记下来，周末再慢慢整理。')}</textarea>`}${fail?'<p class="error-text">连接中断。已识别的文字和剩余录音都已保留。</p>':''}<div class="button-row">${recording?btn('停止录音','stop-record','primary'):fail?btn('重试剩余片段','retry-record','primary'):btn(finishing?'请稍候…':'保存这段文字','save-record','primary',finishing?'disabled':'')}${!recording&&!finishing?btn('移除试用录音','clear-record'):''}</div></div>`}
function finishRecord(fail=false){state.record='finishing';$('recorder').innerHTML=recordHTML();later(()=>{state.record=fail?'failed':'done';state.voice.error=fail;$('recorder')&&($('recorder').innerHTML=recordHTML())},900)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,k=b.dataset.kind;
 if(a==='navigate')navigate(b.dataset.page);else if(a==='back')navigate('ai');else if(a==='close-settings')$('settings-shade').hidden=true;else if(a==='close-modal')closeModal();else if(a==='source'){if(draft.source===b.dataset.source)return;const remoteModel=draft.source==='service'?draft.model:draft.remoteModel;draft={...draft,remoteModel,testing:false,source:b.dataset.source,tested:false,result:null};draft.model=draft.source==='local'?(route==='voice'?'Qwen3-ASR · 0.6B':'Qwen3-Embedding · 0.6B'):(remoteModel??suggestions(route,draft.service)[0]);renderDetail()}
 else if(a==='toggle'){const key=b.dataset.key;if(key==='preload')state.voice.preload=!state.voice.preload;else state[key]=!state[key];b.setAttribute('aria-checked',key==='preload'?state.voice.preload:state[key]);if(key==='mcp')renderMcp();toast('已更新 Demo 设置')}
 else if(a==='test'){if(!draft.model.trim()){toast('请先填写模型名称');return}const urlInput=$('api-url');if(!urlInput.value.trim()||!urlInput.checkValidity()){toast('请先填写有效的 API 地址');urlInput.focus();return}draft.testing=true;draft.result=null;const current=draft,model=draft.model,service=draft.service,url=draft.url,apiKey=draft.apiKey;renderDetail();later(()=>{if(draft!==current||draft.model!==model||draft.service!==service||draft.url!==url||draft.apiKey!==apiKey)return;draft.testing=false;draft.tested=true;draft.result='ok';renderDetail()},900)}
 else if(a==='apply')apply();else if(a==='confirm-index'){closeModal();state.embedding={...state.embedding,...draft,enabled:true};beginIndex();draftFor('embedding');renderDetail();toast('正在建立语义索引，基础搜索继续可用。')}
 else if(a==='index-toggle'){clearTimeout(indexTimer);state.embedding.job=state.embedding.job==='paused'?'indexing':'paused';if(state.embedding.job==='indexing')tickIndex();renderDetail()}
 else if(a==='rebuild'){draft.tested=true;draft.model=state.embedding.model;openModal('重新建立语义索引？','<p class="modal-copy">会重新处理 128 条当前记忆。记忆正文保持原样，基础搜索继续可用。</p>',btn('取消','close-modal')+btn('开始重建','confirm-index','primary'))}
 else if(a==='disable'){state[route].enabled=false;if(route==='embedding')state.embedding.job=null;toast(names[route]+'已关闭，模型文件和记忆保留。');navigate('ai')}
 else if(a==='download'){b.disabled=true;b.textContent='正在下载…';let n=0;const draw=()=>{n+=20;if(route===k&&$('download-status'))$('download-status').innerHTML=progress(n,100);if(n<100)later(draw,380);else{state[k].downloaded=true;toast('模型已下载，可以启用。');if(route===k)renderDetail()}};later(draw,300)}
 else if(a==='try-voice'){state.record='recording';state.recordText=undefined;$('recorder').innerHTML=recordHTML();$('recorder').scrollIntoView({block:'nearest',behavior:'smooth'})}
 else if(a==='stop-record')finishRecord($('scenario').value==='error');else if(a==='retry-record'){if($('voice-text'))state.recordText=$('voice-text').value;finishRecord(false)}else if(a==='save-record'){toast('示例文字已保存到 Demo，正式记忆库未改变。');state.record=null;state.voice.error=false;$('recorder').innerHTML=''}else if(a==='clear-record'){state.record=null;state.voice.error=false;$('recorder').innerHTML=''}
 else if(a==='release')toast('已模拟释放运行内存，下次使用时自动加载。');else if(a==='shortcut'){openModal('设置'+(k==='shortcut'?'唤起':'语音')+'快捷键','<p class="modal-copy">点击下方按键框，按下你想使用的组合键。仅模拟，不注册系统快捷键。</p><button class="kbd" id="shortcut-input" style="width:100%">点击后按下组合键</button>');$('shortcut-input').onclick=()=>{$('shortcut-input').textContent='请按组合键…';$('shortcut-input').focus()};$('shortcut-input').onkeydown=e=>{if(['Control','Shift','Alt','Meta','Tab','Escape'].includes(e.key))return;e.preventDefault();state[k]=[e.ctrlKey?'⌃':'',e.altKey?'⌥':'',e.shiftKey?'⇧':'',e.metaKey?'⌘':'',e.code==='Space'?'Space':e.key.toUpperCase()].filter(Boolean).join(' ');closeModal();renderDesktop();toast('快捷键已在 Demo 中更新')}}
 else if(a==='backup'){toast('正在模拟创建备份…');later(()=>toast('备份预览完成，未读取或导出真实数据。'),800)}else if(a==='restore')openModal('从备份恢复？','<p class="modal-copy">示例备份：Memivy-2026-09-10.zip</p><div class="impact"><strong>包含 124 条记忆、18 段讨论</strong>会先创建当前记忆库的副本，再恢复备份。模型连接和密钥保持不变。</div>',btn('取消','close-modal')+btn('模拟恢复','confirm-restore','primary'));
 else if(a==='confirm-restore'){closeModal();toast('已完成恢复流程演示，正式资料库未改变。')}
 else if(a==='clear-model')openModal('删除已下载的模型？',`<p class="modal-copy">将释放 ${k==='voice'?'1.02 GB':'640 MB'} 磁盘空间。所有 Memivy 资料库共用该文件，再次使用时需要重新下载。</p><div class="impact">当前${names[k]}若使用本地模型，将关闭该功能。记忆正文不会删除。</div>`,btn('取消','close-modal')+btn('删除模型文件','confirm-clear','danger',`data-kind="${k}"`));
 else if(a==='confirm-clear'){state[k].downloaded=false;if(state[k].source==='local')state[k].enabled=false;if(k==='embedding')state.embedding.job=null;closeModal();renderData();toast('已模拟清理模型文件，记忆保留。')}
 else if(a==='repair'){toast('正在模拟修复基础搜索索引…');later(()=>toast('基础搜索索引已修复，记忆正文保持原样。'),800)}
 else if(a==='mcp-test'){b.disabled=true;b.textContent='检查中…';later(()=>{toast('模拟检查通过：保存与检索可用。');renderMcp()},700)}else if(a==='mcp-config')openModal('本地 MCP 连接配置','<p class="modal-copy">下面为示例配置。正式应用会生成实际安装路径。</p><div class="code">{\n  "mcpServers": {\n    "memivy": {\n      "command": "/Applications/Memivy.app/Contents/MacOS/memivy-mcp"\n    }\n  }\n}</div>',btn('完成','close-modal','primary'));
});
document.addEventListener('input',e=>{if(e.target.id==='model-input'&&draft){draft.model=e.target.value;draft.testing=false;const testButton=$('page').querySelector('[data-action=test]');if(testButton){testButton.disabled=false;testButton.textContent='测试连接'}draft.tested=false;draft.result=null;const applyButton=$('page-footer').querySelector('[data-action=apply]');if(applyButton)applyButton.disabled=true;$('test-result').innerHTML=''}if(e.target.id==='tokens'&&draft)draft.tokens=e.target.value;if(e.target.id==='voice-text')state.recordText=e.target.value});
$('scenario').onchange=e=>reset(e.target.value);$('reset').onclick=()=>{reset($('scenario').value);toast('Demo 已重置')};$('open-settings').onclick=()=>{$('settings-shade').hidden=false;navigate('ai')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').open&&!$('settings-shade').hidden){$('settings-shade').hidden=true;$('open-settings').focus()}});
reset();

document.addEventListener('input',e=>{if(draft&&['api-url','api-key'].includes(e.target.id)){draft[e.target.id==='api-url'?'url':'apiKey']=e.target.value;draft.testing=false;const testButton=$('page').querySelector('[data-action=test]');if(testButton){testButton.disabled=false;testButton.textContent='测试连接'}draft.tested=false;draft.result=null;const b=document.querySelector('[data-action="apply"]');if(b)b.disabled=true;$('test-result').innerHTML=''}});
