import {useRef,useState} from "react";
import {call,errorText,native} from "./api";
import {ErrorNotice,Modal} from "./components";
import {Icon} from "../ui";
import {indexLabel,modelNames,type Binding,type Models,type Kind,type EmbeddingStatus,type ConnectionDraft} from "./modelTypes";
import type {VoiceStatus} from "./useVoice";
import VoiceSettings from "./VoiceSettings";
type Props={connectionDraft?:ConnectionDraft|null;setConnectionDraft?:(d:ConnectionDraft|null)=>void;kind:Kind;models:Models;draft:Binding;setDraft:(b:Binding)=>void;embedding:EmbeddingStatus|null;voice:VoiceStatus|null;onSaved:(m:Models)=>void;onModels:(m:Models)=>void;onReconcile?:(m:Models)=>void;onRefresh:()=>Promise<void>;onDesktop:()=>void;onBusy:(v:boolean)=>void};
export default function ModelCapability(p:Props){
 const {kind,models,draft,embedding,voice}=p;
 const [test,setTest]=useState<{token:string;signature:string;revision:string;message:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[rebuild,setRebuild]=useState(false);
 const serial=useRef(0),active=useRef(false);
 const local=draft.source==='local',current=models[kind],enabled=kind==='llm'?!!current:kind==='embedding'?!!(embedding?.enabled||embedding?.preparing):!!voice?.enabled;
 const inline=p.connectionDraft;
 const selected=models.connections.find(c=>c.id===(inline?.id??draft.connection));
 const connectionReady=inline?!!inline.base_url.trim():!!selected;
 function editConnection(patch:Partial<ConnectionDraft>){edit({});p.setConnectionDraft?.({...inline??{id:selected?.id??'',name:modelNames[kind],base_url:selected?.base_url??'',api_key:null,remove:false},...patch})}
 const validTest=test?.signature===JSON.stringify(draft)&&test.revision===models.revision;
 const changed=!!inline||JSON.stringify(current)!==JSON.stringify(draft);
 const indexChanged=kind==='embedding'&&(draft.source!==models.embedding.source||(draft.source==='service'&&(draft.model!==models.embedding.model||draft.dimensions!==models.embedding.dimensions||draft.query_prefix!==models.embedding.query_prefix||(inline?.base_url??selected?.base_url??'').trim().replace(/\/+$/,'')!==(models.connections.find(c=>c.id===models.embedding.connection)?.base_url??'').trim().replace(/\/+$/,''))));
 const localReady=kind==='embedding'?!!embedding&&embedding.downloaded>=embedding.bytes:!!voice?.local_available;
 function edit(patch:Partial<Binding>){serial.current++;setTest(null);p.setDraft({...draft,...patch})}
 async function run(work:()=>Promise<void>){if(active.current)return;active.current=true;setBusy(true);p.onBusy(true);setError('');try{await work()}catch(e){setError(errorText(e))}finally{active.current=false;setBusy(false);p.onBusy(false)}}
 async function testModel(){const n=++serial.current;await run(async()=>{const result=await call<{binding:Binding;token:string;message:string}>('models_test',{revision:models.revision,kind,binding:draft,connection:inline??null});if(n!==serial.current)return;p.setDraft(result.binding);setTest({token:result.token,signature:JSON.stringify(result.binding),revision:models.revision,message:result.message})})}
 async function apply(disable=false){await run(async()=>{try{const m=await call<Models>('models_apply',{revision:models.revision,kind,binding:disable?null:draft,token:validTest?test?.token:null,confirmed:kind==='embedding'});await p.onRefresh();p.onSaved(m)}catch(e){try{p.onReconcile?.(await call<Models>('models_load'));await p.onRefresh()}catch{}throw e}})}
 async function control(action:string){await run(async()=>{await call('embedding_control',{action});await p.onRefresh()})}
 return <><div className="model-detail">
 {kind!=='llm'&&<div className="model-mode-picker">{(['local','service'] as const).map(source=><button key={source} className={draft.source===source?'selected':''} aria-pressed={draft.source===source} disabled={busy} onClick={()=>{if(source!==draft.source)edit({source})}}><Icon name={source==='local'?'desktop':'link'}/><span><strong>{source==='local'?'内置本地模型':'连接模型服务'}</strong><small>{source==='local'?'在这台 Mac 上运行':'自带 API 或自建服务'}</small></span><i/></button>)}</div>}
 {local?<div className="model-local-card"><strong>{kind==='voice'?'Qwen3-ASR':'Qwen3-Embedding'} · 0.6B Q8</strong><p>{kind==='voice'?'中文、英文及多语言 · 约 1.02 GB':'多语言语义检索 · 约 640 MB'}</p><span className="model-badge">{localReady?'已下载，可离线使用':'首次使用需要下载'}</span></div>:<>
 <label>API 地址<input type="url" value={inline?.base_url??selected?.base_url??''} placeholder="https://example.com/v1" autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>editConnection({base_url:e.target.value,api_key:null})}/></label>

 <><label>模型名称<input value={draft.model} placeholder={kind==='voice'?'如 whisper-1 或服务提供的模型 ID':kind==='embedding'?'填写 Embedding 模型 ID':'填写对话模型 ID'} disabled={busy} autoComplete="off" onChange={e=>edit({model:e.target.value})}/></label> <label>API Key<input type="password" value={inline?.api_key??''} placeholder={selected?.has_key&&(!inline||inline.base_url===selected.base_url)?'已保存，留空保留':'本机服务可以留空'} autoComplete="new-password" disabled={busy} onChange={e=>editConnection({api_key:e.target.value||null})}/></label><p className="field-help">填写 OpenAI 兼容服务地址和模型，测试后即可在此启用。</p><button className="outline-button" disabled={!native||busy||!connectionReady||!draft.model.trim()} onClick={()=>void testModel()}>{busy?'处理中…':'测试连接'}</button>{validTest&&<p className="model-test-result" role="status">{test.message}</p>}</>

 </>}
 <p className="model-privacy"><Icon name="lock" size={14}/><span>{local?'内容在这台 Mac 上处理，不发送到模型服务。':kind==='embedding'?'首次建立索引会发送当前记忆正文；之后发送新增、修改内容和搜索问题（含相关记忆与 MCP 检索）。向量索引保存在本机。':kind==='voice'?'录音期间分段发送音频到所选服务。识别文字可修改，只有你提交后才保存。':'使用时发送问题、必要对话和相关记忆；开启自动整理后也会发送新记录和相关背景。'}</span></p>
 {kind==='llm'&&<><div className="setting-line"><div><strong>保存后自动整理</strong><p>关闭期间的记录保留原文，重新开启后不自动补整理。</p></div><button className="model-switch" role="switch" aria-label="保存后自动整理" aria-checked={models.auto_organize} disabled={busy||!native} onClick={()=>void run(async()=>{p.onModels(await call<Models>('models_organize',{revision:models.revision,enabled:!models.auto_organize}))})}><i/></button></div><details><summary>高级设置</summary><label className="checkbox-label"><input type="checkbox" checked={draft.disable_reasoning} disabled={busy} onChange={e=>edit({disable_reasoning:e.target.checked})}/>快速响应（关闭模型推理，端点需支持）</label><label>输出 token 上限<input type="number" min={1} max={1048576} value={draft.max_output_tokens??''} placeholder="使用服务商默认值" disabled={busy} onChange={e=>edit({max_output_tokens:e.target.value?Number(e.target.value):null})}/></label><label>服务商支持的参数<select value={draft.output_token_parameter} disabled={busy} onChange={e=>edit({output_token_parameter:e.target.value as Binding['output_token_parameter']})}><option value="max_tokens">max_tokens</option><option value="max_completion_tokens">max_completion_tokens（含推理额度）</option></select></label></details></>}
 {kind==='embedding'&&<>
 {!local&&<details><summary>高级：查询指令</summary><p className="field-help">通常留空。需要检索指令的模型可按官方要求填写；指令只添加到搜索问题之前。</p><label>查询前缀<textarea value={draft.query_prefix} disabled={busy} maxLength={500} onChange={e=>edit({query_prefix:e.target.value})}/></label><button className="model-text-button" disabled={busy} onClick={()=>edit({query_prefix:'Instruct: Given a question, retrieve relevant personal notes that answer the question\nQuery: '})}>使用 Qwen3-Embedding 推荐指令</button></details>}
 <div className="setting-line"><div><strong>当前语义索引</strong><p>{indexLabel(embedding)}</p></div>{embedding?.paused?<button className="outline-button" disabled={busy} onClick={()=>void control('resume')}>继续</button>:embedding?.error?<button className="outline-button" disabled={busy} onClick={()=>void control('retry')}>重试</button>:embedding?.preparing?<button className="outline-button" disabled={busy} onClick={()=>void control('pause')}>暂停</button>:embedding?.enabled?<button className="model-text-button" disabled={busy} onClick={()=>setRebuild(true)}>重新建立</button>:null}</div>
 {embedding?.preparing&&<progress aria-label="语义检索准备进度" max={embedding.state==='downloading'?embedding.bytes:Math.max(1,embedding.total)} value={embedding.state==='downloading'?embedding.downloaded:embedding.processed}/>}
 {embedding?.preparing&&<button className="model-text-button" disabled={busy} onClick={()=>void control('cancel')}>取消准备</button>}
 <ErrorNotice text={embedding?.error??''}/><p className="field-help">只处理当前记忆，归档、历史、回收站和未保存草稿不参与索引。</p></>}
 {kind==='voice'&&<>{local&&<VoiceSettings controlsOnly/>}<div className="setting-line"><div><strong>语音快捷键</strong><p>主窗口与快捷入口共用模型和草稿规则。</p></div><button className="model-text-button" disabled={busy} onClick={p.onDesktop}>修改快捷键 →</button></div><p className="field-help">启用后，在记录或提问输入框点击麦克风即可试用。单次最长 5 分钟；停止并完成转写后再提交。</p></>}
 <ErrorNotice text={error}/></div>
 <footer className="model-footer"><span>{enabled?<button className="model-text-button" disabled={busy||!native} onClick={()=>void apply(true)}>关闭{modelNames[kind]}</button>:'随时可以关闭，已保存内容保留'}</span><button className="send-button" disabled={busy||!native||(!local&&!validTest)||(!changed&&enabled)} onClick={()=>kind==='embedding'&&(!enabled||indexChanged)?setConfirm(true):void apply()}>{busy?'处理中…':kind==='embedding'&&enabled&&indexChanged?'更换并重建':local&&!localReady&&kind==='embedding'?'下载并启用':enabled?'应用设置':`启用${modelNames[kind]}`}</button></footer>
 {confirm&&<Modal title={enabled?'更换语义检索模型？':'开启语义检索？'} onClose={()=>{if(!busy)setConfirm(false)}}><p>将处理 {embedding?.total??'当前'} 条当前记忆。准备期间仍可记录、阅读和使用基础搜索。</p><p className="model-privacy">{local?'全部在本机处理。':`正文片段将发送给「${models.connections.find(c=>c.id===draft.connection)?.name??'所选服务'}」，后续新增和修改也会增量处理，费用由服务商结算。`}归档、历史、回收站和草稿不参与。</p><ErrorNotice text={error}/><div className="action-row"><button className="outline-button" disabled={busy} onClick={()=>setConfirm(false)}>取消</button><button className="send-button" disabled={busy} onClick={()=>{setConfirm(false);void apply()}}>确认并建立索引</button></div></Modal>}
 {rebuild&&<Modal title="重新建立语义索引？" onClose={()=>setRebuild(false)}><p>将按当前使用的模型重新处理 {embedding?.total} 条当前记忆。模型服务会收到正文片段并可能计费；本地模型在本机处理。过程中使用基础搜索，正文保持原样。</p><div className="action-row"><button className="outline-button" onClick={()=>setRebuild(false)}>取消</button><button className="send-button" onClick={()=>{setRebuild(false);void control('rebuild')}}>开始重建</button></div></Modal>}
 </>;
}
